package org.isf.accounting.test;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "AccountingTest.json")
public interface AccountingTestInterface {

    @Vertex()
    void v_ItensRecuperados();

    @Edge()
    void e_RecuperarPagamentos();

    @Edge()
    void e_RecuperarItens();

    @Vertex()
    void v_BillAtualizado();

    @Vertex()
    void v_Inicio();

    @Edge()
    void e_AtualizarBill();

    @Vertex()
    void v_BillDeletado();

    @Edge()
    void e_RetornarDeItensParaBillCriado();

    @Vertex()
    void v_BillCriado();

    @Edge()
    void e_RetornarDePagamentosParaBillCriado();

    @Edge()
    void e_DeletarBill();

    @Edge()
    void e_CriarBill();

    @Vertex()
    void v_PagamentosRecuperados();
}
